namespace :bootstrap do
      desc "Add the  Categories "
      task :default_category => :environment do
       
        Category.create( :name => 'Artwork', :parent_id => 1 )
         Category.create( :name => 'Auto', :parent_id => 1 )
        Category.create( :name => 'Animals', :parent_id => 1 )
        Category.create( :name => 'Boats', :parent_id => 1 )
        Category.create( :name => 'Funny', :parent_id => 1 )
        Category.create( :name => 'Electronics', :parent_id => 1 )
        Category.create( :name => 'Fitness', :parent_id => 1 )
        Category.create( :name => 'Music',  :parent_id => 1 )
         Category.create( :name => 'Country',  :parent_id => 1 )
          Category.create( :name => 'Pop/Rock',  :parent_id => 1 )
         Category.create( :name => 'Rap', :parent_id => 1 )
        Category.create( :name => 'Electronic',  :parent_id => 1)
         Category.create( :name => 'Sports',  :parent_id => 1 )
         Category.create( :name => 'Extreme',  :parent_id => 1 )
         Category.create( :name => 'Baseball',  :parent_id => 1 )
        Category.create( :name => 'Basketball',  :parent_id => 1 )
        Category.create( :name => 'Football',  :parent_id => 1 )
        Category.create( :name => 'Soccer',  :parent_id => 1 )
        Category.create( :name => 'Hockey',  :parent_id => 1 )
        Category.create( :name => 'Books',  :parent_id => 1 )
         Category.create( :name => 'Business',  :parent_id => 1 )
       Category.create( :name => 'News',  :parent_id => 1 )
       Category.create( :name => 'World News',  :parent_id => 1 )
       Category.create( :name => 'Nature',  :parent_id => 1 )
       Category.create( :name => 'College',  :parent_id => 1 )
       Category.create( :name => 'Movies',  :parent_id => 1 )
         Category.create( :name => 'Television',  :parent_id => 1 )
        Category.create( :name => 'Comedy',  :parent_id => 1 )
        Category.create( :name => 'Drama',  :parent_id => 1 )
        Category.create( :name => 'Suspense/Horror',  :parent_id => 1 )
        Category.create( :name => 'Entertainment World',  :parent_id => 1 )
        Category.create( :name => 'Magic',  :parent_id => 1 )
        Category.create( :name => 'Conspiracies',  :parent_id => 1 )
        Category.create( :name => 'Night Life',  :parent_id => 1 )
        Category.create( :name => 'Self Improvement',  :parent_id => 1 )
        Category.create( :name => 'Internet',  :parent_id => 1 )
        Category.create( :name => 'Internet Technologies',  :parent_id => 1 )
        Category.create( :name => 'Computers',  :parent_id => 1 )
        Category.create( :name => 'Gadgets',  :parent_id => 1 )
        Category.create( :name => 'Architecture',  :parent_id => 1 )
        Category.create( :name => 'Engineering',  :parent_id => 1 )
        Category.create( :name => 'Space',  :parent_id => 1 )
        Category.create( :name => 'Education',  :parent_id => 1 )
        Category.create( :name => 'Random Fact Of The Day',  :parent_id => 1 )
        Category.create( :name => 'Science',  :parent_id => 1 )
        Category.create( :name => 'Photography',  :parent_id => 1 )
        Category.create( :name => 'Medical',  :parent_id => 1 )
        Category.create( :name => 'Miscellaneous',  :parent_id => 1 )
        Category.create( :name => 'Homes',  :parent_id => 1 )
       
        
      end

      task :all => [:default_category]
      
    end
